# Generated by Django 6.0.4 on 2026-04-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Cash')], default='cash', max_length=20),
            preserve_default=False,
        ),
    ]
