# Generated by Django 6.0.4 on 2026-04-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_category', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('executive', 'Executive Suite'), ('presidential', 'Presidential Suite')], max_length=20)),
                ('room_status', models.CharField(choices=[('not_occupied', 'Not Occupied'), ('occupied', 'Occupied')], default='not_occupied', max_length=15)),
            ],
        ),
    ]
